security:
    encoders:
        Adshares\AdsOperator\Document\User:
            algorithm: bcrypt
    providers:
        user_provider:
            mongodb: { class: Adshares\AdsOperator\Document\User, property: email }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
            pattern:  ^/api/%api_version%/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/%api_version%/auth/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api/
            stateless: true
            anonymous: true
            provider: user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/%api_version%/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/%api_version%/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/%api_version%/auth/users/[0-9a-z]+/confirm-change-email/[0-9a-z]+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/%api_version%/auth, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/api/%api_version%/blockexplorer, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
