Adshares\AdsOperator\Document\Info:
    exclusion_policy: ALL
    properties:
        genesisTime:
            expose: true
            type: int
        blockLength:
            expose: true
            type: int
        lastBlockId:
            expose: true
            type: string
        totalSupply:
            expose: true
            type: float
        circulatingSupply:
            expose: true
            type: float
        unpaidDividend:
            expose: true
            type: float
        nodes:
            expose: true
            type: int
        accounts:
            expose: true
            type: int
        messages:
            expose: true
            type: int
        transactions:
            expose: true
            type: int
