@startuml
hide footbox
title 2FA check

participant "ADS Node" as Node
participant Operator
participant "ADS Client" as ADS

Node -> Operator: check transaction (bin data)
activate Operator

Operator -> Operator: check transaction
alt transaction exists

    Operator -> Operator: check 2FA status
    Operator -> Operator: check user
    Operator --> Node: [valid status & user] valid response

else transaction not exists

    Operator -> ADS: decode transaction
    activate ADS
    ADS --> Operator: transaction info
    deactivate ADS
    Operator -> Operator: save transaction

end
    Operator --> Node: invalid response
    deactivate Operator

@enduml